language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo
before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make
  - sudo make install
  - sudo ldconfig
  - cd ..
script:
  - cargo test --all-features
