---
name: CurrentApplicationInfo
description: Information about the current application and its owner.
fields:
  - name: description
    type: string
  - name: icon
    optional: true
    type: string
  - name: id
    type: UserId
  - name: name
    type: string
  - name: owner
    type: User
  - name: rpc_origins
    array: true
    default: Vec::default()
    type: string
