---
name: UserSettings
description: User settings usually used to influence client behavior.
fields:
  - name: convert_emoticons
    type: bool
  - name: enable_tts_command
    type: bool
  - name: friend_source_flags
    type: FriendSourceFlags
  - name: inline_attachment_media
    type: bool
  - name: inline_embed_media
    type: bool
  - name: locale
    type: string
  - name: message_display_compact
    type: bool
  - name: render_embeds
    type: bool
  - name: restricted_guilds
    array: true
    type: GuildId
  - name: show_current_game
    type: bool
  - name: status
    custom: OnlineStatus::decode_str
    default: OnlineStatus::Online
    type: OnlineStatus
  - name: theme
    type: string
decode: false
